### ISSUE TITLE
dig v2

### ISSUE THREAD

**Issue by faddat** [notional-labs/dig#157]
Dig v2 is mainly a cleanup and scope reduction release.

1) epochs did not work, let's take e'm out
2) we really do need minimum commission fees.  Notional was built on Notional's osmo commission fees and﻿ that's something that we want to see happen for Dig's validators.
3) Cosmos-SDK v0.45.0

Dig community/team:

How many other state-breaking changes can we pack into v0.45.0?

:)

-J

**Comment by nguyenvuong1122000** [comment]
I removed it in branch :

https://github.com/notional-labs/dig/tree/epoch-remove

**Comment by faddat** [comment]
Any idea what upgrade handlers look like for this?

Let's make a checklist for the dig v2 upgrade:

- [ ] Remove epochs
- [ ] Enforce minimum commissions
- [ ] Use canonical secp256k1 signing (let's not use modified cosmos-sdk anymore if possible)
- [ ] Testnet
- [ ] Governance Proposal
- [ ] Upgrade

**Comment by romelukaku** [comment]
yeah, I agree

**Comment by nguyenvuong1122000** [comment]
Enforce minimum commissions in branch : https://github.com/notional-labs/cosmos-sdk/tree/v0.45-1-rum

I think we should use a modify cosmos-sdk (don't use mainline cosmos-sdk)

**Comment by faddat** [comment]
Why not use mainline?

**Comment by nguyenvuong1122000** [comment]
hmm, i don't see minimum comissions in cosmos-sdk v0.45.1
https://github.com/cosmos/cosmos-sdk/blob/v0.45.1/x/staking/types/staking.pb.go

**Comment by faddat** [comment]
well 💩 Best fork off again, then. 

Can you check this code against the mincomission code on juno?

An edge case was discovered and it was a bit nasty

**Comment by nguyenvuong1122000** [comment]
Cosmwasm done. In https://github.com/notional-labs/dig/tree/digv2

I instance some contract and test with it. Contract work :100:

**Comment by romelukaku** [comment]
what is  Version Import Paths

**Comment by nghuyenthevinh2000** [comment]
@nguyenvuong1122000 
What is dig testnet node? so I can set up faucet bot

**Comment by faddat** [comment]
hey!
