### ISSUE TITLE
Setting up Validator

### ISSUE THREAD

**Issue by joelsmith-2019** [notional-labs/dig#166]
I am trying to setup a node on digv1 as I want to be in the active set, but I am not able too. I have tried changing up the reset point, my keyname, and init moniker to no luck.

**Steps to reproduce**
git clone https://github.com/notional-labs/dig && cd dig/
git checkout master
git reset --hard a5a396998b6894265d095a1977ed095ecac64bcc
go mod tidy
go install ./...

digd keys add joel
digd init carbonator --chain-id dig-1

wget -O ~/.dig/config/genesis.json https://github.com/notional-labs/dig/raw/master/networks/mainnets/dig-1/genesis.json

digd start --p2p.seeds 37b2839da4463b22a51b1fe20d97992164270eba@62.171.157.192:26656,e2c96b96d4c3a461fb246edac3b3cdbf47768838@65.21.202.37:6969 --p2p.persistent_peers 33f4788e1c6a378b929c66f31e8d253b9fd47c47@194.163.154.251:26656,64eccffdc60a206227032d3a021fbf9dfc686a17@194.163.156.84:26656,be7598b2d56fb42a27821259ad14aff24c40f3d2@172.16.152.118:26656,f446e37e47297ce9f8951957d17a2ae9a16db0b8@137.184.67.162:26656,ab2fa2789f481e2856a5d83a2c3028c5b215421d@144.91.117.49:26656,e9e89250b40b4512237c77bd04dc76c06a3f8560@185.214.135.205:26656,1539976f4ee196f172369e6f348d60a6e3ec9e93@159.69.147.189:26656,85316823bee88f7b05d0cfc671bee861c0237154@95.217.198.243:26656,eb55b70c9fd8fc0d5530d0662336377668aab3f9@185.194.219.128:26656

**Error**
12:51AM INF Reconnecting to peer addr={"id":"ab2fa2789f481e2856a5d83a2c3028c5b215421d","ip":"144.91.117.49","port":26656} module=p2p
12:51AM INF Dialing peer address={"id":"ab2fa2789f481e2856a5d83a2c3028c5b215421d","ip":"144.91.117.49","port":26656} module=p2p
12:51AM ERR dialing failed (attempts: 1): auth failure: secret conn failed: read tcp 65.108.125.182:43496->185.214.135.205:26656: i/o timeout addr={"id":"e9e89250b40b4512237c77bd04dc76c06a3f8560","ip":"185.214.135.205","port":26656} module=pex
12:51AM ERR dialing failed (attempts: 1): auth failure: secret conn failed: read tcp 65.108.125.182:38408->185.194.219.128:26656: i/o timeout addr={"id":"eb55b70c9fd8fc0d5530d0662336377668aab3f9","ip":"185.194.219.128","port":26656} module=pex

**Comment by Reecepbcups** [comment]
Can confirm, have same issue on my backup machine as well.

Attempted following commit's & tags to no luck
- a5a396998b6894265d095a1977ed095ecac64bcc
- 3dd3218251f6059b5b14138fc273f166da07523a
- 8871b56b41df5be94306d11bc3d1a8e4505d96ac
- 626bbb44940e7a637919c4878fced1173ec34b61
- v1.1.0
- v1.0.1

Some versions I was able to get it to sync up blocks once, but on stop and start again it would error out
Each time with unique moniker as well, is this maybe a tendermint issue @faddat ? 

I figured it was an outdated addrbook but since it does sync sometimes, its not that

**Comment by nguyenvuong1122000** [comment]
you can try that :
 digd start --p2p.seeds 37b2839da4463b22a51b1fe20d97992164270eba@62.171.157.192:26656,e2c96b96d4c3a461fb246edac3b3cdbf47768838@65.21.202.37:6969 --p2p.persistent_peers 33f4788e1c6a378b929c66f31e8d253b9fd47c47@194.163.154.251:26656,64eccffdc60a206227032d3a021fbf9dfc686a17@194.163.156.84:26656,be7598b2d56fb42a27821259ad14aff24c40f3d2@172.16.152.118:26656,f446e37e47297ce9f8951957d17a2ae9a16db0b8@137.184.67.162:26656,ab2fa2789f481e2856a5d83a2c3028c5b215421d@144.91.117.49:26656,e9e89250b40b4512237c77bd04dc76c06a3f8560@185.214.135.205:26656,1539976f4ee196f172369e6f348d60a6e3ec9e93@159.69.147.189:26656,85316823bee88f7b05d0cfc671bee861c0237154@95.217.198.243:26656,eb55b70c9fd8fc0d5530d0662336377668aab3f9@185.194.219.128:26656,1f7e10351548dd399e2ac906cafd89f5dc15f37a@188.40.72.115:2220,8e5a38b1576921c1cf9891b39f1c46764711dd8a@168.119.91.22:2220 

Seem old peer died.

**Comment by stake98** [comment]
I get the error when I set up a validator

```
11:48AM INF starting ABCI with Tendermint
11:48AM INF Starting multiAppConn service impl=multiAppConn module=proxy
11:48AM INF Starting localClient service connection=query impl=localClient module=abci-client
11:48AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
11:48AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
11:48AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
11:48AM INF Starting EventBus service impl=EventBus module=events
11:48AM INF Starting PubSub service impl=PubSub module=pubsub
11:48AM INF Starting IndexerService service impl=IndexerService module=txindex
11:48AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
11:48AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
11:48AM INF asserting crisis invariants inv=0/11 module=x/crisis name=staking/module-accounts
11:48AM INF asserting crisis invariants inv=1/11 module=x/crisis name=staking/nonnegative-power
11:48AM INF asserting crisis invariants inv=2/11 module=x/crisis name=staking/positive-delegation
11:48AM INF asserting crisis invariants inv=3/11 module=x/crisis name=staking/delegator-shares
11:48AM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/nonnegative-outstanding
11:48AM INF asserting crisis invariants inv=5/11 module=x/crisis name=distribution/can-withdraw
11:48AM INF asserting crisis invariants inv=6/11 module=x/crisis name=distribution/reference-count
11:48AM INF asserting crisis invariants inv=7/11 module=x/crisis name=distribution/module-account
11:48AM INF asserting crisis invariants inv=8/11 module=x/crisis name=gov/module-account
11:48AM INF asserting crisis invariants inv=9/11 module=x/crisis name=bank/nonnegative-outstanding
11:48AM INF asserting crisis invariants inv=10/11 module=x/crisis name=bank/total-supply
11:48AM INF asserted all invariants duration=0.595848 height=0 module=x/crisis
11:48AM INF created new capability module=ibc name=ports/transfer
11:48AM INF port binded module=x/ibc/port port=transfer
11:48AM INF claimed capability capability=1 module=transfer name=ports/transfer
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
```

**Comment by stake98** [comment]
I have the same error
```
12:31PM INF Dialing peer address={"id":"1539976f4ee196f172369e6f348d60a6e3ec9e93","ip":"159.69.147.189","port":26656} module=p2p
12:31PM ERR dialing failed (attempts: 6): dial tcp 194.163.154.251:26656: connect: connection refused addr={"id":"33f4788e1c6a378b929c66f31e8d253b9fd47c47","ip":"194.163.154.251","port":26656} module=pex
2:31PM ERR dialing failed (attempts: 6): auth failure: conn.ID (fec3524b68e228ac1f1f87ba287de9b4f04a8690) dialed ID (8e5a38b1576921c1cf9891b39f1c46764711dd8a) mismatch addr={"id":"8e5a38b1576921c1cf9891b39f1c46764711dd8a","ip":"168.119.91.22","port":2220} module=pex
12:31PM ERR dialing failed (attempts: 6): auth failure: conn.ID (0d83b9159805de0aa0a3a0c213362de565dad64e) dialed ID (85316823bee88f7b05d0cfc671bee861c0237154) mismatch addr={"id":"85316823bee88f7b05d0cfc671bee861c0237154","ip":"95.217.198.243","port":26656} module=pex
```

**Comment by joelsmith-2019** [comment]
> you can try that : digd start --p2p.seeds 37b2839da4463b22a51b1fe20d97992164270eba@62.171.157.192:26656,e2c96b96d4c3a461fb246edac3b3cdbf47768838@65.21.202.37:6969 --p2p.persistent_peers 33f4788e1c6a378b929c66f31e8d253b9fd47c47@194.163.154.251:26656,64eccffdc60a206227032d3a021fbf9dfc686a17@194.163.156.84:26656,be7598b2d56fb42a27821259ad14aff24c40f3d2@172.16.152.118:26656,f446e37e47297ce9f8951957d17a2ae9a16db0b8@137.184.67.162:26656,ab2fa2789f481e2856a5d83a2c3028c5b215421d@144.91.117.49:26656,e9e89250b40b4512237c77bd04dc76c06a3f8560@185.214.135.205:26656,1539976f4ee196f172369e6f348d60a6e3ec9e93@159.69.147.189:26656,85316823bee88f7b05d0cfc671bee861c0237154@95.217.198.243:26656,eb55b70c9fd8fc0d5530d0662336377668aab3f9@185.194.219.128:26656,1f7e10351548dd399e2ac906cafd89f5dc15f37a@188.40.72.115:2220,8e5a38b1576921c1cf9891b39f1c46764711dd8a@168.119.91.22:2220
> 
> Seem old peer died.

Thank you, that fixed the issue!

**Comment by stake98** [comment]
> you can try that : digd start --p2p.seeds 37b2839da4463b22a51b1fe20d97992164270eba@62.171.157.192:26656,e2c96b96d4c3a461fb246edac3b3cdbf47768838@65.21.202.37:6969 --p2p.persistent_peers 33f4788e1c6a378b929c66f31e8d253b9fd47c47@194.163.154.251:26656,64eccffdc60a206227032d3a021fbf9dfc686a17@194.163.156.84:26656,be7598b2d56fb42a27821259ad14aff24c40f3d2@172.16.152.118:26656,f446e37e47297ce9f8951957d17a2ae9a16db0b8@137.184.67.162:26656,ab2fa2789f481e2856a5d83a2c3028c5b215421d@144.91.117.49:26656,e9e89250b40b4512237c77bd04dc76c06a3f8560@185.214.135.205:26656,1539976f4ee196f172369e6f348d60a6e3ec9e93@159.69.147.189:26656,85316823bee88f7b05d0cfc671bee861c0237154@95.217.198.243:26656,eb55b70c9fd8fc0d5530d0662336377668aab3f9@185.194.219.128:26656,1f7e10351548dd399e2ac906cafd89f5dc15f37a@188.40.72.115:2220,8e5a38b1576921c1cf9891b39f1c46764711dd8a@168.119.91.22:2220
> 
> Seem old peer died.

It doesn't work. Please check again. Thank you.

**Comment by mgialong215** [comment]
these 2 will do:
```
1f7e10351548dd399e2ac906cafd89f5dc15f37a@188.40.72.115:2220,41feb52e4a7ec0f8f29c4ceab83440511efca74c@142.132.196.223:2220
```
