### ISSUE TITLE
DIG v2.0.0 Alpha RasPi Error

### ISSUE THREAD

**Issue by dotwin1981** [notional-labs/dig#169]
I have just briefly tested whether the testnet would run on a Raspberry Pi. But the v2.0.0 alpha says no.

# github.com/CosmWasm/wasmvm/api
/usr/bin/ld: skipping incompatible ../go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.0.0-beta5/api/libwasmvm.so when searching for -lwasmvm
/usr/bin/ld: cannot find -lwasmvm: No such file or directory
/usr/bin/ld: skipping incompatible ../go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.0.0-beta5/api/libwasmvm.so when searching for -lwasmvm
collect2: error: ld returned 1 exit status

**Comment by dotwin1981** [comment]
This is known, but then some validators have massive problems, because some use a RasPi currently. These are then shot down with the update!

**Comment by faddat** [comment]
@dotwin1981 it was that, or no cosmwasm
