### ISSUE TITLE
Interchain accounts (v2 roadmap)

### ISSUE THREAD

**Issue by faddat** [notional-labs/dig#170]
Dig v2 was a little delayed, but for great reason!

We can now add interchain accounts to dig, but in order to do that we will need to fully remove Starport from dig because of the nodule layout.

**Comment by hieuvubk** [comment]
@nghuyenthevinh2000 can you invite me repo. I want to promote my pr. Realize that the ica module doesn't have a cli available to interact with. I imported more intertx module for easier interaction but same logic

**Comment by faddat** [comment]
@hieuvubk yes, please
