### ISSUE TITLE
add eth-address on cli

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [notional-labs/dig#82]
The story is that modified keplr for dig has added support for eth address. But, it is not the same for cli. 

Objective: "digd keys add temp" must return eth address instead of "dig1981hjrhewkrhqwr".

The library to convert. @romelukaku knows

- [ ] extract which library from @romelukaku

**Comment by nghuyenthevinh2000** [comment]
@nghuyenthevinh2000 
I am working on this now

**Comment by faddat** [comment]
Cool!  

Please talk with Osmosis:


https://github.com/osmosis-labs/osmosis/issues/590
https://github.com/osmosis-labs/osmosis/issues/589

**Comment by faddat** [comment]
@nghuyenthevinh2000 I would like dig1 addresses to be the primary though.  Maybe have a flag letting you specify an eth address.

**Comment by nghuyenthevinh2000** [comment]
thanks for the info, I will talk to them

**Comment by nghuyenthevinh2000** [comment]
[prodv2.tar.gz](https://github.com/notional-labs/dig/files/7617176/prodv2.tar.gz)

**Comment by MasterPi-2124** [comment]
strangely that Minh's branch is working while main branch doesn't

**Comment by nghuyenthevinh2000** [comment]
inconsistency in dig version that supports eth address gen

**Comment by nguyenvuong1122000** [comment]
it's working in main branch now

**Comment by faddat** [comment]
Ok, I am going to close this and please reopen if there are problems.

**Comment by nguyenvuong1122000** [comment]
We need change eth code, to verify metamask signature.

**Comment by nghuyenthevinh2000** [comment]
done
