### ISSUE TITLE
Implement decay mechanism for airdrop

### ISSUE THREAD

**Issue by stephen94k** [notional-labs/dig#83]
Airdrops that are not claimed or utilized could represent a large % of the float, and these unclaimed airdrops may severely negatively impact token economics. See Ion, for example, 2/3 of total float exists in inactive wallets.

We should implement a decay mechanic so that active and participating users can claim their airdrops, and after a period of time, the claimable amount decreases to 0. 

Proposed claimable airdrop amount by time frame after launch:

Option 1: Short Decay
0-14 days 100% 
15-30 days 50%
After 30 days: 0%

Option 2: Longer Decay
0-30 days 100% 
30-45 days 50%
After 30 days: 0%

**Comment by faddat** [comment]
Like it and request that you submit a gov-prop to nuke 0-txn accounts at the 30 day mark.
